"""Generate a quiet, synthetic Opus fixture for the optional board stress test.

Requires ffmpeg on PATH. No recordings or network access are used.
"""
import pathlib
import subprocess
import tempfile

target = pathlib.Path(__file__).with_name("tone_fixture.h")
with tempfile.TemporaryDirectory() as temp:
    ogg = pathlib.Path(temp) / "tone.ogg"
    subprocess.run([
        "ffmpeg", "-hide_banner", "-loglevel", "error", "-f", "lavfi",
        "-i", "sine=frequency=660:sample_rate=24000:duration=1",
        "-af", "volume=0.15", "-c:a", "libopus", "-b:a", "48000",
        "-vbr", "off", "-frame_duration", "20", str(ogg),
    ], check=True)
    data = ogg.read_bytes()

packets, partial, pos = [], bytearray(), 0
while pos < len(data):
    assert data[pos:pos + 4] == b"OggS"
    segments = data[pos + 26]
    sizes = data[pos + 27:pos + 27 + segments]
    pos += 27 + segments
    for size in sizes:
        partial.extend(data[pos:pos + size])
        pos += size
        if size < 255:
            packets.append(bytes(partial))
            partial.clear()
packets = packets[2:]  # OpusHead / OpusTags
assert packets and all(len(p) == 120 for p in packets)
rows = ["{" + ",".join(str(x) for x in p) + "}" for p in packets]
target.write_text(
    "/* Generated by generate_fixture.py; synthetic 660 Hz test tone. */\n"
    "static const uint8_t power_opus_fixture[][120] = {\n" + ",\n".join(rows) + "\n};\n",
    encoding="utf-8",
)
print(f"Generated {len(packets)} Opus packets: {target}")
